---
title: "CMS Fast Facts"
subtitle: "April 2025 Release"
logo: assets/CMS_logo.jpeg
format: 
  dashboard:
    fig-format: png
    orientation: columns
    theme:
      - cosmo
      - assets/ff_format.scss
    nav-buttons:
      - icon: github
        href: "#"
        aria-label: "Source Code"
    scrolling: false
    dpi: 330
knitr:
  opts_chunk: 
    dev: ragg_png
resources:
  - assets/CMS_logo.jpeg
execute:
  echo: false
  warning: false
  message: false
---

```{r}
#| label: dependencies
#| include: false

#dependencies
library(tidyverse)
library(scales, warn.conflicts = FALSE)
library(systemfonts)
library(ggrepel)
library(waffle)
library(gt)
library(gtExtras)

#add colors

source("Scripts/color_system.R")

# Register the OTF font used for pictograms
register_font(
  name  = "FontAwesome7Solid",
  plain = "/Users/c0xu/Library/Fonts/Font Awesome 7 Free-Solid-900.otf"
)

# register_variant(
#   "Source Sans 3 Black",
#   family = "Source Sans 3",
#   weight = "heavy"
# )

```

```{r}
#| label: load_data
#| include: false

#load each the data needed for each tab, stored in a list element
context <- read_rds("Dataout/context.rds")
beneficiaries <- read_rds("Dataout/beneficiaries.rds")
cost_sharing <- read_rds("Dataout/cost_sharing.rds")

```

# Context

## Column

### Row {height=20%}

```{r}
#| label: ban_nhe
#| content: valuebox
#| title: "National Health Expenditures (NHE)"
#| icon: heart-pulse-fill
#| color: primary

list(
  value = scales::label_number(
    prefix   = "$",
    suffix   = "T",
    accuracy = 0.1,
    big.mark = ","
  )(context$bans[["nhe_total"]]/1e3),
  subtitle = context$years[["nhe_yr"]]
)
```

### Row
```{r}
#| label: share-gdp
#| title: "NHE share of GDP"

ggplot() +
  geom_rect(
    aes(
      xmin = 0,
      xmax = 12,
      ymin = 0,
      ymax = 100 / 12
    ),
    color =  "#A6A6A6",
    fill = "white", linewidth = 1.1
  ) +
  geom_rect(
    aes(
      xmin = 0,
      xmax = sqrt(context[["nhe_gdp_share"]]*100),
      ymin = 0,
      ymax = sqrt(context[["nhe_gdp_share"]]*100)
    ),
    fill = ff_colors$base[["green"]]
  ) +
  labs(title = label_percent()(context[["nhe_gdp_share"]])) +
  coord_equal() +
  theme_void() +
  theme(
    plot.title = element_text(
      size = 30, hjust = .5, 
      family = "Source Sans 3", face = "bold",
      color = ff_colors$scales$steel["900"]
      )
    )


```

### Row {height="20%"}
```{r}
#| label: per_capita
#| title: "NHE per capita"

# Value and scale
per_capita <- context[["nhe_pc"]]
n_icons <- round(per_capita / 1000)

# Build pictogram data
icons <- tibble::tibble(
  index = 1:n_icons,
  x     = ((index - 1) %% 8) + 1,
  y     = -((index - 1) %/% 8)
)

# Plot
ggplot(icons, aes(x = x, y = y)) +
  geom_text(
    label  = "\uf0d6",               # FA "money-bill" glyph
    family = "FontAwesome7Solid",
    size   = 22,
    color  = ff_colors$base[["green"]]
  ) +
  scale_x_continuous(expand = expansion(add = 0.5)) +  
  scale_y_continuous(expand = expansion(add = 0.5)) + 
  coord_fixed(ratio = 1) + 
  labs(
    title    = label_currency()(context[["nhe_pc"]]),
    subtitle = "Each icon ≈ $1,000"
  ) +
  theme_void() +
  theme(
    plot.title    = element_text(family = "Source Sans 3", face = "bold", size = 30, hjust = 0.5, color = ff_colors$elements[["title"]]),
    plot.subtitle = element_text(family = "Source Sans 3", size = 25, hjust = 0.5, color = ff_colors$elements[["subtitle"]]),
    plot.margin   = margin(10, 10, 10, 10)  # minimal outer margin
  )
```

## Column

### Row {height=20%}
```{r}
#| label: ban_health-insurance
#| content: valuebox
#| title: "Health Insurance"
#| icon: shield-plus
#| color: primary

list(
  value = scales::label_number(
    prefix   = "$",
    suffix   = "T",
    accuracy = 0.1,
    big.mark = ","
  )(context$bans[["health_insurance"]]/1e3),
  subtitle = context$years[["nhe_yr"]]
)
```

### Row

```{r}
#| label: insurnace_bar
#| title: "Health Expenditures by Payer"
#| fig-height: 8        # Increase this to stretch the plot vertically
#| out.height: "100%"   # Tells the output to fill the container
#| fig-width: 6

context[["df_insurance_trend"]] |> 
  select(category, latest_value) |> 
  mutate(
    latest_value = latest_value * 1e9,
    fill_color = 
      case_when(
        str_detect(category, "Medicare") ~ ff_colors$base[["azure"]],
        str_detect(category, "Medicaid") ~ ff_colors$base[["teal"]],
        str_detect(category, "CHIP") ~ ff_colors$base[["plum"]],
        TRUE ~ "#A6A6A6"
        ) 
  ) |> 
  ggplot(aes(latest_value, fct_reorder(category, latest_value, .fun = sum), fill = fill_color)) +
  geom_blank(aes(latest_value * 1.3)) +
  geom_col() +
  geom_text(
    # aes(label = label_comma(prefix = "$", suffix = " B")(latest_value)),
    aes(label = label_comma(prefix = "$", scale_cut = cut_short_scale())(latest_value)),
    hjust = -.2, size = 6, family = "Source Sans 3", color = ff_colors$elements[["annotation"]]
    ) + 
  facet_wrap(~fct_reorder(category, latest_value, .fun = sum, .desc = TRUE), ncol = 1, scales = "free_y") +
  scale_x_continuous(expand = c(.005, .005)) +
  scale_fill_identity() +
  coord_cartesian(clip = "off") +
  labs(x = NULL, y = NULL) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    strip.text = element_text(
      family = "Source Sans 3",
      color = ff_colors$elements[["annotation"]],
      size = 20, hjust = 0),
    panel.spacing = unit(0, "lines"),
    panel.grid = element_blank()
  )


```

## Column

### Row {height=20%}
```{r}
#| label: ban_fed_spend
#| content: valuebox
#| title: "CMS Federal Program Spending"
#| icon: bank
#| color: primary

list(
  value = scales::label_number(
    prefix   = "$",
    suffix   = "T",
    accuracy = 0.1,
    big.mark = ","
  )(context$bans[["fed_spend"]]/1e6),
  subtitle = context$years[["fed_spend_yr"]]
)
```

### Row

#### Row
```{r}
#| label: fed_spend_pictogram
#| title: "CMS Spending by Category"

context[["df_spend"]] |> 
  filter(group == "Spend") |> 
  mutate(squares = round(share * 100)) |> 
  ggplot(aes(fill = category, values = squares)) +
  geom_waffle(
    n_rows  = 10,
    size    = 1.5,
    colour  = "white",
    flip    = FALSE
  ) +
  scale_fill_manual(values = c(
    "Medicare Benefits" = ff_colors$base[["azure"]],
    "Total Medicaid"    = ff_colors$base[["teal"]],
    "CHIP"              = ff_colors$base[["plum"]],
    "Other Spending"    = ff_colors$scales$charcoal[["200"]]  #"#a6a6a6"
  )) +
  labs(
    subtitle = "Each square represents ~1% of total",
    # caption  = "Source: CMS",
    fill     = NULL
  ) +
  coord_fixed() +
  theme_void() +
  theme(
    plot.title    = element_text(face = "bold", size = 30, hjust = 0.5),
    plot.subtitle = element_text(size = 25, hjust = 0.5, color = "gray40"),
    legend.position = "none"
  )
```

#### Row

```{r}
#| label: spend_table

context[["df_spend"]] |> 
  select(-share) |> 
  mutate(
    value = value * 1e6,
    fill_color = recode_values(
     category,
    "Medicare Benefits" ~ ff_colors$base[["azure"]],
    "Total Medicaid"    ~ ff_colors$base[["teal"]],
    "CHIP"              ~ ff_colors$base[["plum"]],
    "Other Spending"    ~ ff_colors$scales$charcoal[["200"]]  #"#a6a6a6"
    )
   ) |> 
  relocate(fill_color, .before = 1) |> 
  gt(groupname_col =  "group") |> 
  cols_label(
    fill_color = "",
    category = "",
    value = "Gross Outlays"
  ) |> 
  fmt_currency(
    columns = value,
    decimals = 1,
    suffixing = TRUE 
    ) |> 
 text_transform(
    locations = cells_body(columns = fill_color),
    fn = function(x) {
      glue::glue(
        "<span style='display:inline-block; width:14px; height:14px;
         border-radius:3px; background-color:{x};'></span>"
      )
    }
  ) |>
  cols_align(align = "center", columns = fill_color) |>
  cols_width(fill_color ~ px(24)) |>
  opt_row_striping(row_striping = FALSE) |> 
  tab_options(
    table.border.top.style            = "none",
    table.border.bottom.style         = "none",
    column_labels.border.top.style    = "none",
    column_labels.border.bottom.style = "none",
    data_row.padding                  = px(5)
  )
```


### Row {height="20%"}
```{r}
#| label: fte
#| title: "CMS Full-Time Equivalents (FTEs)"

n_units <- round(context[["fte"]] / 1000)

icons <- tibble(
  index = 1:(n_units),
  x     = index,
  y     = 0
)

icons |> 
  ggplot(aes(x = x, y = y)) +
  geom_text(
    label  = "\uf007",              # Font Awesome "person" / user icon
    family = "FontAwesome7Solid",
    size   = 30,
    color  = ff_colors$scales$steel["900"]
  ) +
  scale_x_continuous(expand = expansion(add = 0.5)) +
  scale_y_continuous(expand = expansion(add = 0.5)) +
  labs(
    title    = label_comma()(context[["fte"]]),
    subtitle = "Each icon represents ~1,000 FTEs"
  ) +
  theme_void() +
  theme(
    plot.title    = element_text(face = "bold", size = 60, hjust = 0.5),
    plot.subtitle = element_text(size = 25, hjust = 0.5, color = "gray40"),
    plot.caption  = element_text(size = 9, hjust = 0.5, color = "gray60"),
    plot.margin   = margin(10, 10, 10, 10)
  )

```

# Beneficiaries {orientation="rows"}

## Row {height=25%}

```{r}
#| label: ban_medicare_ab
#| content: valuebox
#| title: "Medicare Parts A/B"
#| icon: heart-fill
#| color: primary

list(
  value = scales::label_number(
    suffix   = "M",
    # accuracy = 0.1,
    big.mark = ","
  )(beneficiaries$bans[["medicare_ab"]]),
  subtitle = beneficiaries$years[["ban_year"]]
)
```

```{r}
#| label: ban_medicare_d
#| content: valuebox
#| title: "Medicare Part D"
#| icon: capsule-pill
#| color: primary

list(
  value = scales::label_number(
    suffix   = "M",
    # accuracy = 0.1,
    big.mark = ","
  )(beneficiaries$bans[["medicare_d"]]),
  subtitle = beneficiaries$years[["ban_year"]]
)
```

```{r}
#| label: ban_medicaid
#| content: valuebox
#| title: "Medicaid & CHIP"
#| icon: people-fill
#| color: primary

list(
  value = scales::label_number(
    suffix   = "M",
    # accuracy = 0.1,
    big.mark = ","
  )(beneficiaries$bans[["medicaid"]]),
  subtitle = beneficiaries$years[["ban_year"]]
)
```

## Row
```{r}
#| label: medicare_type
#| title: "Medicare Advantage Overtaking Original Medicare"

beneficiaries[["df_medicare_type_trend"]] |>
  mutate(
    lab_og = case_when(year == min(year) | year == max(year) ~ label_number(suffix = "M")(original_medicare)),
    lab_ma = case_when(year == min(year) | year == max(year) ~ label_number(suffix = "M")(medicare_advantage))
  ) |> 
  ggplot(aes(x = year)) +
  geom_ribbon(
    aes(
      ymin = pmin(original_medicare, medicare_advantage),
      ymax = pmax(original_medicare, medicare_advantage)
    ),
    fill = ff_colors$base["warmgray"], #"lightgray",
    alpha = 0.3
  ) +
  geom_line(aes(y = original_medicare, color = "Original Medicare")) +
  geom_line(aes(y = medicare_advantage, color = "Medicare Advantage")) + 
  geom_point(aes(y = original_medicare, color = "Original Medicare")) +
  geom_point(aes(y = medicare_advantage, color = "Medicare Advantage")) +
  geom_text(
    aes(y = original_medicare, label = lab_og), 
    family = "Source Sans 3",
    vjust = -1, na.rm = TRUE
    ) +
  geom_text(
    aes(y = medicare_advantage, label = lab_ma), 
    family = "Source Sans 3", color = ff_colors$elements["annotation"],
    vjust = 1.4, na.rm = TRUE
    ) +
  scale_color_manual(
    values = c(
      "Original Medicare" = ff_colors$scales$cobolt[["900"]],
      "Medicare Advantage" = ff_colors$scales$cobolt[["200"]]
      )
      )+
  labs(
    x = NULL, y = NULL,
    # title = "Medicare Advantage Overtaking Original Medicare"
    ) +
  coord_cartesian(clip = "off") +
  theme_minimal(base_size = 22) +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.y = element_blank()
  )
  
```

```{r}
#| label: medicaid_types
#| title: "Trends in Medicaid Sub-Populations"

beneficiaries[["df_medicaid_type_trends"]] |> 
  ggplot(aes(year, value, group = category, fill = fill_color, color = fill_color)) +
  geom_area(alpha = .4) +
  geom_line() +
  geom_point(aes(y = val_pt), na.rm = TRUE) +
  geom_text(
    aes(label = lab_start), 
    vjust = -1, na.rm = TRUE, 
    family = "Source Sans 3", 
    color = ff_colors$elements[["annotation"]]
    ) +
  geom_text(
    aes(label = lab_end), 
    vjust = -1, na.rm = TRUE, 
    family = "Source Sans 3",
    color = ff_colors$elements[["annotation"]]
    ) +
  facet_grid(~fct_reorder2(category, year, value)) +
  scale_x_continuous(breaks = range(unique(beneficiaries[["df_medicaid_type_trends"]]$year), na.rm = TRUE)) +
  scale_color_identity() +
  scale_fill_identity() +
  coord_cartesian(clip = "off") +
  labs(x = NULL, y = NULL) +
  theme_minimal(base_size = 22) +
  theme(
    legend.position = "none",
    strip.text = element_text(
      color = ff_colors$elements[["title"]],
      face = "bold"
      ),
    axis.text.y = element_blank(),
    panel.grid = element_blank(),
  )
```

## Row
```{r}
#| label: orig_medicare_utilization
#| title: Medicare Utilization

beneficiaries[["df_medicare_util"]] |> 
  filter_out(category %in% c("Part A", "Part B")) |>
  mutate(category = ifelse(category == "Part D", "Total", category)) |> 
  ggplot(aes(metric, zscore, group = category, color = group)) +
  geom_line() +
  geom_point() +
  geom_text(
    aes(label = lab_ben),
    hjust = 1.1,
    family = "Source Sans 3",
    color = ff_colors$elements[["annotation"]],
    na.rm = TRUE
  ) +
  geom_text(
    aes(label = lab_exp),
    hjust = -.2,
    family = "Source Sans 3",
    color = ff_colors$elements[["annotation"]],
    na.rm = TRUE
  ) +
  facet_wrap(~group) +
  scale_color_manual(
    values = 
      c(
        ff_colors$scales$cobolt[["200"]],
        ff_colors$scales$cobolt[["700"]],
        ff_colors$scales$cobolt[["900"]]
      )) +
  labs(x = NULL, y = NULL) +
  coord_cartesian(clip = "off") +
  theme_minimal(base_size = 22) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_blank(),
    axis.text.y = element_blank(),
    legend.position = "none",
    strip.text = element_text(face = "bold", color = ff_colors$elements[["title"]])
  )

# df_medicare_util |>
#   filter_out(category %in% c("Part A", "Part B")) |>
#   select(-zscore, -starts_with('lab_')) |>
#   pivot_wider(
#     names_from = metric
#   ) |>
#   ggplot(aes(beneficiaries, payments, color = group)) +
#   geom_point() +
#   geom_text(aes(label = category)) +
#   # facet_wrap(~group) +
#   labs(x = "Persons Served (millions)", y = "Payments (billions)") +
#   theme_minimal()
```
```{r}
#| label: medicaid_exp
#| title: Medicaid Expenditures

medicaid_exp_tot <- beneficiaries[['df_medicaid_exp']] |> 
  filter(category == "All Services") |> 
  pull() 

beneficiaries[['df_medicaid_exp']] |> 
  filter(category != "All Services") |> 
  ggplot(aes(value, fct_reorder(category, value))) +
  geom_blank(aes(x = value *1.3)) +
  geom_col(fill = ff_colors$base[["teal"]]) +
  geom_text(
    aes(
      label = label_comma(1, prefix = "$", suffix = " B")(value)),
      hjust = -.1, family = "Source Sans 3", color = ff_colors$elements[["annotation"]]
  ) +
  coord_cartesian(clip = "off") +
  scale_x_continuous(expand = c(.005, .005)) +
  labs(
    x = NULL, y = NULL,
    title = str_glue('All Services = {label_comma(1, prefix = "$", suffix = " B")(medicaid_exp_tot)}')   
  ) +
  theme_minimal(base_size = 22) +
  theme(
    axis.text.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold", color = ff_colors$elements[["title"]])
  )
```

# Cost Sharing {orientation="rows"}

## Row {height="20%"}

```{r}
#| label: ban_part_a_benes
#| content: valuebox
#| title: "Part A Persons Served"
#| icon: people-fill
#| color: primary

list(
  cost_sharing$bans[["part_a_beneficiaries"]],
  subtitle = cost_sharing$years
)
```


```{r}
#| label: ban_part_b_benes
#| content: valuebox
#| title: "Part B Persons Served"
#| icon: people-fill
#| color: primary

list(
  cost_sharing$bans[["part_b_beneficiaries"]],
  subtitle = cost_sharing$years
)
```



```{r}
#| label: ban_part_d_benes
#| content: valuebox
#| title: "Part D Beneficiaries"
#| icon: people-fill
#| color: primary

list(
  cost_sharing$bans[["part_d_beneficiaries"]],
  subtitle = cost_sharing$years
)
```

## Row {height="20%"}
```{r}
#| label: ban_part_a_exp
#| content: valuebox
#| title: "Part A Program Payments"
#| icon: people-fill
#| color: primary

list(
  cost_sharing$bans[["part_a_payments"]],
  subtitle = cost_sharing$years
)
```


```{r}
#| label: ban_part_b_exp
#| content: valuebox
#| title: "Part B Program Payments"
#| icon: people-fill
#| color: primary

list(
  cost_sharing$bans[["part_b_payments"]],
  subtitle = cost_sharing$years
)
```

```{r}
#| label: ban_part_d_exp
#| content: valuebox
#| title: "Part B Expenditures"
#| icon: people-fill
#| color: primary

list(
  cost_sharing$bans[["part_d_payments"]],
  subtitle = cost_sharing$years
)
```

## Row

```{r}
#| label: dumbell_charts
#| title: "Medicare Deductibles, Coinsurance, Premiums"

cost_sharing[["df_cs_trend"]] |> 
  ggplot(aes(value, fct_reorder(category, order, .fun = max, .na_rm = TRUE), group = ln_group)) +
  geom_path(color = ff_colors$scales$cobolt[["200"]], na.rm = TRUE) +
  geom_point(
    color = "white",
    stroke = 1.1, 
    size = 4,
    na.rm = TRUE
  ) +
  geom_point(
    aes(fill = fill_color), na.rm = TRUE,
    shape = 21, 
    color = ff_colors$base[["azure"]], 
    stroke = 1.1, 
    size = 4, alpha = .4) +
  geom_text(
    aes(x = mid_pt, label = delta_lab),
    na.rm = TRUE,
    family = "Source Sans 3",
    color = ff_colors$elements[["annotation"]],
    vjust = -1.1
  ) + 
  # facet_wrap(~group, nrow = 1, scales = "free") +
  facet_wrap(group ~ ., ncol = 1, scales = "free", space = "free_y", strip.position = "top") +
  labs(x = NULL, y = NULL) +
  scale_fill_identity() +
  scale_x_continuous(label = label_currency()) +
  theme_minimal() +
  theme(
    axis.text = element_text(family = "Source Sans 3"),
    strip.text = element_text(family = "Source Sans 3", face = "bold", hjust = 0),
    strip.placement = "outside",
    panel.spacing = unit(0, "lines")
  )
```

# Providers